### PR TITLE
Add SkinShuffle, Snow Under Trees

### PR DESCRIPTION
**Pull request by IMB11**
https://modrinth.com/mod/skinshuffle - "Effortless in-game skin customization and management—change, store, and customize your skins with SkinShuffle. Instant skin changes available on compatible servers."
https://modrinth.com/mod/snow-under-trees-remastered/ - "Adds snow under trees in snowy biomes, making the biomes more immersive."

MRU is a library mod dependency of both.

### CODE REVIEW

**Comment by cassiancc** [comment]
Since your mods are marked as All Rights Reserved, do we have permission to include these in the modpack jar? We don't currently have a page listing all mods, or a traditional changelog since releases are done through GitHub Actions.

**Comment by IMB11** [comment]
Yeah. They're on modrinth which explicitly allows distribution of anything uploaded, no need to overthink.

**Comment by IMB11** [comment]
Yep, mentioned in discord, can just install skinshuffle server-side only for the folks who want to have it on their clients.

**Comment by IMB11** [comment]
Removed skinshuffle

**Review by cassiancc — APPROVED** [review]

**Pull request merged**
